resources:
- agent.yaml
# - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_agent_config.yaml
  name: agent-netplan-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
