apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-metallb
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-metallb-role
rules:
- apiGroups:
  - network-connector.sylvaproject.org
  resources:
  - inbounds
  - inbounds/status
  - inbounds/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - metallb.io
  resources:
  - ipaddresspools
  - bgpadvertisements
  - l2advertisements
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-metallb-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-metallb-role
subjects:
- kind: ServiceAccount
  name: platform-metallb
  namespace: system
