apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
namePrefix: network-operator-
resources:
- ../../config/crd
- ../../config/rbac
- ../../config/cert
- ../../config/operator
- ../../config/agent-cra-frr
- ../../config/agent-netplan
- ../../config/healthcheck
- ../../config/platform-coil
- ../../config/platform-metallb
- ../../config/webhook
- intent_rbac.yaml
patches:
- path: manager_webhook_patch.yaml
