version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - errcheck
    - errorlint
    - funlen
    - ginkgolinter
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 25
    funlen:
      lines: 100
      statements: 60
    gocognit:
      min-complexity: 33
    gocritic:
      disabled-checks:
        - regexpSimplify
        - whyNoLint
        - unnamedResult
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    godot:
      scope: toplevel
      exclude:
        - ^ \+.*
        - ^ ANCHOR.*
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
      no-unaliased: true
    nolintlint:
      require-specific: true
      allow-unused: false
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: bare-return
          disabled: true
        - name: cognitive-complexity
          arguments:
            - 33
          severity: error
          disabled: false
        - name: comment-spacings
          arguments:
            - +kubebuilder
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 18
          severity: error
          disabled: false
        - name: file-header
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: function-length
          arguments:
            - 60
            - 0
          severity: error
          disabled: false
        - name: if-return
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - io.Writer.Write
            - bytes.Buffer.Write
            - bytes.Buffer.WriteString
            - hash.Write
          severity: warning
          disabled: false
        - name: use-any
          disabled: true
        - name: use-errors-new
          disabled: true
        # Disable new v2 rules to maintain backward compatibility
        - name: use-waitgroup-go
          disabled: true
        - name: unnecessary-format
          disabled: true
        - name: var-naming
          disabled: true
        - name: deep-exit
          disabled: true
        - name: identical-switch-branches
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1003
        - -QF1001
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: cmd/manager/main.go
        text: Function 'main' has too many statements
      - path: cmd/manager/main.go
        text: 'function-length: maximum number of statements per function exceeded; max \d+ but got \d+'
      - path: (.+)/unix/(coil|frr|nl)\.go
        text: 'ST1003: should not use ALL_CAPS in Go names; use CamelCase instead'
      - path: (.+)/unix/(coil|frr|nl)\.go
        text: 'var-naming: don''t use ALL_CAPS in Go names; use CamelCase'
      - path: (.+)/nl/(route|layer2)\.go
        text: import-alias-naming:.+\(schiff_unix\).*$
      - path: (.+)_test\.go
        text: 'unchecked-type-assertion:'
      - path: (.+)_test\.go
        text: 'import-alias-naming:'
      - path: (.+)_test\.go
        text: 'dot-imports:'
      - path: (.+)\.go
        text: string `vrf` has (\d+) occurrences, make it a constant
      - path: (.+)/monitoring/frr\.go
        text: Function '\w+' is too long
      - path: (.+)/monitoring/frr\.go
        text: Function '\w+' has too many statements
      - path: (.+)/nl/route\.go
        text: Function '\w+' has too many statements
      - path: (.+)/nl/route\.go
        text: cyclomatic complexity \d+ of func `\w+` is high
      - path: (.+)/nl/route\.go
        text: 'cyclomatic: function \w+ has cyclomatic complexity \d+'
      - path: (.+)/nl/route\.go
        text: calculated cyclomatic complexity for function \w+ is \d+, max is \d+
      # Exclude package-directory-mismatch for directories with hyphens
      - path: pkg/cra-frr/
        text: 'package-directory-mismatch:'
      - path: pkg/cra-vsr/
        text: 'package-directory-mismatch:'
      # Exclude enforce-switch-style for existing code
      - linters:
          - revive
        text: 'enforce-switch-style:'
      # Exclude unhandled-error for test files
      - path: (.+)_test\.go
        text: 'unhandled-error:'
      # Exclude new noctx patterns for existing code (v2 detects more patterns)
      - linters:
          - noctx
        text: 'net/http.NewRequest must not be called'
      - linters:
          - noctx
        text: 'net.Dial must not be called'
      - linters:
          - noctx
        text: 'os/exec.Command must not be called'
      # Exclude prealloc for existing code
      - linters:
          - prealloc
        path: pkg/cra-vsr/
      - linters:
          - prealloc
        path: pkg/helpers/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
