---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  # Ignore vendor if present
  vendor/
  # Ignore binaries
  bin/
  # Ignore config directories with generated content
  config/crd/
