// Copied verbatim from kubevirt/kubevirt v1.4.0, pkg/hooks/info/api_info.proto
// (Apache License 2.0), with only a go_package option added. The proto package
// name is part of the gRPC wire contract with virt-launcher and must not be
// changed.
//
// Regenerate with:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          pkg/kubevirthook/pb/*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: pkg/kubevirthook/pb/api_info.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoParams) Reset() {
	*x = InfoParams{}
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoParams) ProtoMessage() {}

func (x *InfoParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoParams.ProtoReflect.Descriptor instead.
func (*InfoParams) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_info_proto_rawDescGZIP(), []int{0}
}

type InfoResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the hook used by virt-launcher to compare it with requested hooks
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// hookPoints is a list of subscribed hook points
	HookPoints []*HookPoint `protobuf:"bytes,3,rep,name=hookPoints,proto3" json:"hookPoints,omitempty"`
	// versions is a list of implemented hook Callbacks service versions
	Versions      []string `protobuf:"bytes,4,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResult) Reset() {
	*x = InfoResult{}
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResult) ProtoMessage() {}

func (x *InfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResult.ProtoReflect.Descriptor instead.
func (*InfoResult) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_info_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResult) GetHookPoints() []*HookPoint {
	if x != nil {
		return x.HookPoints
	}
	return nil
}

func (x *InfoResult) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type HookPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name represents name of the subscribed hook point
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// priority is used to sort hooks prior to their execution (second key is the name)
	Priority      int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookPoint) Reset() {
	*x = HookPoint{}
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookPoint) ProtoMessage() {}

func (x *HookPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookPoint.ProtoReflect.Descriptor instead.
func (*HookPoint) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_info_proto_rawDescGZIP(), []int{2}
}

func (x *HookPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookPoint) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_pkg_kubevirthook_pb_api_info_proto protoreflect.FileDescriptor

const file_pkg_kubevirthook_pb_api_info_proto_rawDesc = "" +
	"\n" +
	"\"pkg/kubevirthook/pb/api_info.proto\x12\x13kubevirt.hooks.info\"\f\n" +
	"\n" +
	"InfoParams\"|\n" +
	"\n" +
	"InfoResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\n" +
	"hookPoints\x18\x03 \x03(\v2\x1e.kubevirt.hooks.info.HookPointR\n" +
	"hookPoints\x12\x1a\n" +
	"\bversions\x18\x04 \x03(\tR\bversions\";\n" +
	"\tHookPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority2P\n" +
	"\x04Info\x12H\n" +
	"\x04Info\x12\x1f.kubevirt.hooks.info.InfoParams\x1a\x1f.kubevirt.hooks.info.InfoResultBDZBgithub.com/telekom/das-schiff-network-operator/pkg/kubevirthook/pbb\x06proto3"

var (
	file_pkg_kubevirthook_pb_api_info_proto_rawDescOnce sync.Once
	file_pkg_kubevirthook_pb_api_info_proto_rawDescData []byte
)

func file_pkg_kubevirthook_pb_api_info_proto_rawDescGZIP() []byte {
	file_pkg_kubevirthook_pb_api_info_proto_rawDescOnce.Do(func() {
		file_pkg_kubevirthook_pb_api_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_kubevirthook_pb_api_info_proto_rawDesc), len(file_pkg_kubevirthook_pb_api_info_proto_rawDesc)))
	})
	return file_pkg_kubevirthook_pb_api_info_proto_rawDescData
}

var file_pkg_kubevirthook_pb_api_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_kubevirthook_pb_api_info_proto_goTypes = []any{
	(*InfoParams)(nil), // 0: kubevirt.hooks.info.InfoParams
	(*InfoResult)(nil), // 1: kubevirt.hooks.info.InfoResult
	(*HookPoint)(nil),  // 2: kubevirt.hooks.info.HookPoint
}
var file_pkg_kubevirthook_pb_api_info_proto_depIdxs = []int32{
	2, // 0: kubevirt.hooks.info.InfoResult.hookPoints:type_name -> kubevirt.hooks.info.HookPoint
	0, // 1: kubevirt.hooks.info.Info.Info:input_type -> kubevirt.hooks.info.InfoParams
	1, // 2: kubevirt.hooks.info.Info.Info:output_type -> kubevirt.hooks.info.InfoResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_kubevirthook_pb_api_info_proto_init() }
func file_pkg_kubevirthook_pb_api_info_proto_init() {
	if File_pkg_kubevirthook_pb_api_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_kubevirthook_pb_api_info_proto_rawDesc), len(file_pkg_kubevirthook_pb_api_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_kubevirthook_pb_api_info_proto_goTypes,
		DependencyIndexes: file_pkg_kubevirthook_pb_api_info_proto_depIdxs,
		MessageInfos:      file_pkg_kubevirthook_pb_api_info_proto_msgTypes,
	}.Build()
	File_pkg_kubevirthook_pb_api_info_proto = out.File
	file_pkg_kubevirthook_pb_api_info_proto_goTypes = nil
	file_pkg_kubevirthook_pb_api_info_proto_depIdxs = nil
}
