// Copied verbatim from kubevirt/kubevirt v1.4.0,
// pkg/hooks/v1alpha3/api_v1alpha3.proto (Apache License 2.0), with only a
// go_package option added. The proto package name is part of the gRPC wire
// contract with virt-launcher and must not be changed.
//
// v1alpha3 is the newest hook version virt-launcher negotiates; it adds
// Shutdown over v1alpha2 and leaves OnDefineDomain unchanged.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: pkg/kubevirthook/pb/api_v1alpha3.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnDefineDomainParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domainXML is original libvirt domain specification
	DomainXML []byte `protobuf:"bytes,1,opt,name=domainXML,proto3" json:"domainXML,omitempty"`
	// vmi is VirtualMachineInstance is object of virtual machine currently processed by virt-launcher, it is encoded as JSON
	Vmi           []byte `protobuf:"bytes,2,opt,name=vmi,proto3" json:"vmi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnDefineDomainParams) Reset() {
	*x = OnDefineDomainParams{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnDefineDomainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnDefineDomainParams) ProtoMessage() {}

func (x *OnDefineDomainParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnDefineDomainParams.ProtoReflect.Descriptor instead.
func (*OnDefineDomainParams) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{0}
}

func (x *OnDefineDomainParams) GetDomainXML() []byte {
	if x != nil {
		return x.DomainXML
	}
	return nil
}

func (x *OnDefineDomainParams) GetVmi() []byte {
	if x != nil {
		return x.Vmi
	}
	return nil
}

type OnDefineDomainResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domainXML is processed libvirt domain specification
	DomainXML     []byte `protobuf:"bytes,1,opt,name=domainXML,proto3" json:"domainXML,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnDefineDomainResult) Reset() {
	*x = OnDefineDomainResult{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnDefineDomainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnDefineDomainResult) ProtoMessage() {}

func (x *OnDefineDomainResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnDefineDomainResult.ProtoReflect.Descriptor instead.
func (*OnDefineDomainResult) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{1}
}

func (x *OnDefineDomainResult) GetDomainXML() []byte {
	if x != nil {
		return x.DomainXML
	}
	return nil
}

type PreCloudInitIsoParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cloudInitNoCloudSource is an object of CloudInitNoCloudSource encoded as JSON
	// This is a legacy field to ensure backwards compatibility. New code should use cloudInitData instead.
	CloudInitNoCloudSource []byte `protobuf:"bytes,1,opt,name=cloudInitNoCloudSource,proto3" json:"cloudInitNoCloudSource,omitempty"`
	// vmi is VirtualMachineInstance is object of virtual machine currently processed by virt-launcher, it is encoded as JSON
	Vmi []byte `protobuf:"bytes,2,opt,name=vmi,proto3" json:"vmi,omitempty"`
	// cloudInitData is an object of CloudInitData encoded as JSON
	CloudInitData []byte `protobuf:"bytes,3,opt,name=cloudInitData,proto3" json:"cloudInitData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCloudInitIsoParams) Reset() {
	*x = PreCloudInitIsoParams{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCloudInitIsoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCloudInitIsoParams) ProtoMessage() {}

func (x *PreCloudInitIsoParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCloudInitIsoParams.ProtoReflect.Descriptor instead.
func (*PreCloudInitIsoParams) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{2}
}

func (x *PreCloudInitIsoParams) GetCloudInitNoCloudSource() []byte {
	if x != nil {
		return x.CloudInitNoCloudSource
	}
	return nil
}

func (x *PreCloudInitIsoParams) GetVmi() []byte {
	if x != nil {
		return x.Vmi
	}
	return nil
}

func (x *PreCloudInitIsoParams) GetCloudInitData() []byte {
	if x != nil {
		return x.CloudInitData
	}
	return nil
}

type PreCloudInitIsoResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cloudInitNoCloudSource is an object of CloudInitNoCloudSource encoded as JSON
	// This is a legacy field to ensure backwards compatibility. New code should use cloudInitData instead.
	CloudInitNoCloudSource []byte `protobuf:"bytes,1,opt,name=cloudInitNoCloudSource,proto3" json:"cloudInitNoCloudSource,omitempty"`
	// cloudInitData is an object of CloudInitData encoded as JSON
	CloudInitData []byte `protobuf:"bytes,3,opt,name=cloudInitData,proto3" json:"cloudInitData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCloudInitIsoResult) Reset() {
	*x = PreCloudInitIsoResult{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCloudInitIsoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCloudInitIsoResult) ProtoMessage() {}

func (x *PreCloudInitIsoResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCloudInitIsoResult.ProtoReflect.Descriptor instead.
func (*PreCloudInitIsoResult) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{3}
}

func (x *PreCloudInitIsoResult) GetCloudInitNoCloudSource() []byte {
	if x != nil {
		return x.CloudInitNoCloudSource
	}
	return nil
}

func (x *PreCloudInitIsoResult) GetCloudInitData() []byte {
	if x != nil {
		return x.CloudInitData
	}
	return nil
}

type ShutdownParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownParams) Reset() {
	*x = ShutdownParams{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownParams) ProtoMessage() {}

func (x *ShutdownParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownParams.ProtoReflect.Descriptor instead.
func (*ShutdownParams) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{4}
}

type ShutdownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResult) Reset() {
	*x = ShutdownResult{}
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResult) ProtoMessage() {}

func (x *ShutdownResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResult.ProtoReflect.Descriptor instead.
func (*ShutdownResult) Descriptor() ([]byte, []int) {
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP(), []int{5}
}

var File_pkg_kubevirthook_pb_api_v1alpha3_proto protoreflect.FileDescriptor

const file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDesc = "" +
	"\n" +
	"&pkg/kubevirthook/pb/api_v1alpha3.proto\x12\x17kubevirt.hooks.v1alpha3\"F\n" +
	"\x14OnDefineDomainParams\x12\x1c\n" +
	"\tdomainXML\x18\x01 \x01(\fR\tdomainXML\x12\x10\n" +
	"\x03vmi\x18\x02 \x01(\fR\x03vmi\"4\n" +
	"\x14OnDefineDomainResult\x12\x1c\n" +
	"\tdomainXML\x18\x01 \x01(\fR\tdomainXML\"\x87\x01\n" +
	"\x15PreCloudInitIsoParams\x126\n" +
	"\x16cloudInitNoCloudSource\x18\x01 \x01(\fR\x16cloudInitNoCloudSource\x12\x10\n" +
	"\x03vmi\x18\x02 \x01(\fR\x03vmi\x12$\n" +
	"\rcloudInitData\x18\x03 \x01(\fR\rcloudInitData\"u\n" +
	"\x15PreCloudInitIsoResult\x126\n" +
	"\x16cloudInitNoCloudSource\x18\x01 \x01(\fR\x16cloudInitNoCloudSource\x12$\n" +
	"\rcloudInitData\x18\x03 \x01(\fR\rcloudInitData\"\x10\n" +
	"\x0eShutdownParams\"\x10\n" +
	"\x0eShutdownResult2\xcc\x02\n" +
	"\tCallbacks\x12n\n" +
	"\x0eOnDefineDomain\x12-.kubevirt.hooks.v1alpha3.OnDefineDomainParams\x1a-.kubevirt.hooks.v1alpha3.OnDefineDomainResult\x12q\n" +
	"\x0fPreCloudInitIso\x12..kubevirt.hooks.v1alpha3.PreCloudInitIsoParams\x1a..kubevirt.hooks.v1alpha3.PreCloudInitIsoResult\x12\\\n" +
	"\bShutdown\x12'.kubevirt.hooks.v1alpha3.ShutdownParams\x1a'.kubevirt.hooks.v1alpha3.ShutdownResultBDZBgithub.com/telekom/das-schiff-network-operator/pkg/kubevirthook/pbb\x06proto3"

var (
	file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescOnce sync.Once
	file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescData []byte
)

func file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescGZIP() []byte {
	file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescOnce.Do(func() {
		file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDesc), len(file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDesc)))
	})
	return file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDescData
}

var file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_kubevirthook_pb_api_v1alpha3_proto_goTypes = []any{
	(*OnDefineDomainParams)(nil),  // 0: kubevirt.hooks.v1alpha3.OnDefineDomainParams
	(*OnDefineDomainResult)(nil),  // 1: kubevirt.hooks.v1alpha3.OnDefineDomainResult
	(*PreCloudInitIsoParams)(nil), // 2: kubevirt.hooks.v1alpha3.PreCloudInitIsoParams
	(*PreCloudInitIsoResult)(nil), // 3: kubevirt.hooks.v1alpha3.PreCloudInitIsoResult
	(*ShutdownParams)(nil),        // 4: kubevirt.hooks.v1alpha3.ShutdownParams
	(*ShutdownResult)(nil),        // 5: kubevirt.hooks.v1alpha3.ShutdownResult
}
var file_pkg_kubevirthook_pb_api_v1alpha3_proto_depIdxs = []int32{
	0, // 0: kubevirt.hooks.v1alpha3.Callbacks.OnDefineDomain:input_type -> kubevirt.hooks.v1alpha3.OnDefineDomainParams
	2, // 1: kubevirt.hooks.v1alpha3.Callbacks.PreCloudInitIso:input_type -> kubevirt.hooks.v1alpha3.PreCloudInitIsoParams
	4, // 2: kubevirt.hooks.v1alpha3.Callbacks.Shutdown:input_type -> kubevirt.hooks.v1alpha3.ShutdownParams
	1, // 3: kubevirt.hooks.v1alpha3.Callbacks.OnDefineDomain:output_type -> kubevirt.hooks.v1alpha3.OnDefineDomainResult
	3, // 4: kubevirt.hooks.v1alpha3.Callbacks.PreCloudInitIso:output_type -> kubevirt.hooks.v1alpha3.PreCloudInitIsoResult
	5, // 5: kubevirt.hooks.v1alpha3.Callbacks.Shutdown:output_type -> kubevirt.hooks.v1alpha3.ShutdownResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_kubevirthook_pb_api_v1alpha3_proto_init() }
func file_pkg_kubevirthook_pb_api_v1alpha3_proto_init() {
	if File_pkg_kubevirthook_pb_api_v1alpha3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDesc), len(file_pkg_kubevirthook_pb_api_v1alpha3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_kubevirthook_pb_api_v1alpha3_proto_goTypes,
		DependencyIndexes: file_pkg_kubevirthook_pb_api_v1alpha3_proto_depIdxs,
		MessageInfos:      file_pkg_kubevirthook_pb_api_v1alpha3_proto_msgTypes,
	}.Build()
	File_pkg_kubevirthook_pb_api_v1alpha3_proto = out.File
	file_pkg_kubevirthook_pb_api_v1alpha3_proto_goTypes = nil
	file_pkg_kubevirthook_pb_api_v1alpha3_proto_depIdxs = nil
}
