// Copied verbatim from kubevirt/kubevirt v1.4.0,
// pkg/hooks/v1alpha3/api_v1alpha3.proto (Apache License 2.0), with only a
// go_package option added. The proto package name is part of the gRPC wire
// contract with virt-launcher and must not be changed.
//
// v1alpha3 is the newest hook version virt-launcher negotiates; it adds
// Shutdown over v1alpha2 and leaves OnDefineDomain unchanged.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: pkg/kubevirthook/pb/api_v1alpha3.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Callbacks_OnDefineDomain_FullMethodName  = "/kubevirt.hooks.v1alpha3.Callbacks/OnDefineDomain"
	Callbacks_PreCloudInitIso_FullMethodName = "/kubevirt.hooks.v1alpha3.Callbacks/PreCloudInitIso"
	Callbacks_Shutdown_FullMethodName        = "/kubevirt.hooks.v1alpha3.Callbacks/Shutdown"
)

// CallbacksClient is the client API for Callbacks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallbacksClient interface {
	OnDefineDomain(ctx context.Context, in *OnDefineDomainParams, opts ...grpc.CallOption) (*OnDefineDomainResult, error)
	PreCloudInitIso(ctx context.Context, in *PreCloudInitIsoParams, opts ...grpc.CallOption) (*PreCloudInitIsoResult, error)
	Shutdown(ctx context.Context, in *ShutdownParams, opts ...grpc.CallOption) (*ShutdownResult, error)
}

type callbacksClient struct {
	cc grpc.ClientConnInterface
}

func NewCallbacksClient(cc grpc.ClientConnInterface) CallbacksClient {
	return &callbacksClient{cc}
}

func (c *callbacksClient) OnDefineDomain(ctx context.Context, in *OnDefineDomainParams, opts ...grpc.CallOption) (*OnDefineDomainResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnDefineDomainResult)
	err := c.cc.Invoke(ctx, Callbacks_OnDefineDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbacksClient) PreCloudInitIso(ctx context.Context, in *PreCloudInitIsoParams, opts ...grpc.CallOption) (*PreCloudInitIsoResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCloudInitIsoResult)
	err := c.cc.Invoke(ctx, Callbacks_PreCloudInitIso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callbacksClient) Shutdown(ctx context.Context, in *ShutdownParams, opts ...grpc.CallOption) (*ShutdownResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResult)
	err := c.cc.Invoke(ctx, Callbacks_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbacksServer is the server API for Callbacks service.
// All implementations must embed UnimplementedCallbacksServer
// for forward compatibility.
type CallbacksServer interface {
	OnDefineDomain(context.Context, *OnDefineDomainParams) (*OnDefineDomainResult, error)
	PreCloudInitIso(context.Context, *PreCloudInitIsoParams) (*PreCloudInitIsoResult, error)
	Shutdown(context.Context, *ShutdownParams) (*ShutdownResult, error)
	mustEmbedUnimplementedCallbacksServer()
}

// UnimplementedCallbacksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallbacksServer struct{}

func (UnimplementedCallbacksServer) OnDefineDomain(context.Context, *OnDefineDomainParams) (*OnDefineDomainResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnDefineDomain not implemented")
}
func (UnimplementedCallbacksServer) PreCloudInitIso(context.Context, *PreCloudInitIsoParams) (*PreCloudInitIsoResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreCloudInitIso not implemented")
}
func (UnimplementedCallbacksServer) Shutdown(context.Context, *ShutdownParams) (*ShutdownResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedCallbacksServer) mustEmbedUnimplementedCallbacksServer() {}
func (UnimplementedCallbacksServer) testEmbeddedByValue()                   {}

// UnsafeCallbacksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallbacksServer will
// result in compilation errors.
type UnsafeCallbacksServer interface {
	mustEmbedUnimplementedCallbacksServer()
}

func RegisterCallbacksServer(s grpc.ServiceRegistrar, srv CallbacksServer) {
	// If the following call pancis, it indicates UnimplementedCallbacksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Callbacks_ServiceDesc, srv)
}

func _Callbacks_OnDefineDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnDefineDomainParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbacksServer).OnDefineDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Callbacks_OnDefineDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbacksServer).OnDefineDomain(ctx, req.(*OnDefineDomainParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callbacks_PreCloudInitIso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCloudInitIsoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbacksServer).PreCloudInitIso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Callbacks_PreCloudInitIso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbacksServer).PreCloudInitIso(ctx, req.(*PreCloudInitIsoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callbacks_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbacksServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Callbacks_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbacksServer).Shutdown(ctx, req.(*ShutdownParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Callbacks_ServiceDesc is the grpc.ServiceDesc for Callbacks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Callbacks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.hooks.v1alpha3.Callbacks",
	HandlerType: (*CallbacksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnDefineDomain",
			Handler:    _Callbacks_OnDefineDomain_Handler,
		},
		{
			MethodName: "PreCloudInitIso",
			Handler:    _Callbacks_PreCloudInitIso_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Callbacks_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/kubevirthook/pb/api_v1alpha3.proto",
}
