---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-t-caas-telekom-com-v1alpha1-vrfrouteconfiguration
  failurePolicy: Fail
  name: vvrfrouteconfiguration.kb.io
  rules:
  - apiGroups:
    - network.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vrfrouteconfigurations
  sideEffects: None
