// Copyright 2025.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: workloadcni.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkloadPort is the datapath payload for a routed attachment.
type WorkloadPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface is the moved interface name inside the CRA network namespace.
	// VSR references it as infra-<interface>.
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// gateway_v4 is the on-link IPv4 gateway address (with prefix length).
	GatewayV4 string `protobuf:"bytes,2,opt,name=gateway_v4,json=gatewayV4,proto3" json:"gateway_v4,omitempty"`
	// gateway_v6 is the on-link IPv6 gateway address (with prefix length).
	GatewayV6 string `protobuf:"bytes,3,opt,name=gateway_v6,json=gatewayV6,proto3" json:"gateway_v6,omitempty"`
	// host_routes are the workload host addresses (/32, /128) reachable via the
	// interface.
	HostRoutes []string `protobuf:"bytes,4,rep,name=host_routes,json=hostRoutes,proto3" json:"host_routes,omitempty"`
	// mtu is the MTU the attachment requested (the CNI config's mtu, which the
	// plugin also applied to the workload-side interface). The CRA needs it to
	// size the interfaces it derives from the port, and to reject a request the
	// L2 domain cannot carry.
	Mtu           uint32 `protobuf:"varint,8,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadPort) Reset() {
	*x = WorkloadPort{}
	mi := &file_workloadcni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadPort) ProtoMessage() {}

func (x *WorkloadPort) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadPort.ProtoReflect.Descriptor instead.
func (*WorkloadPort) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadPort) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *WorkloadPort) GetGatewayV4() string {
	if x != nil {
		return x.GatewayV4
	}
	return ""
}

func (x *WorkloadPort) GetGatewayV6() string {
	if x != nil {
		return x.GatewayV6
	}
	return ""
}

func (x *WorkloadPort) GetHostRoutes() []string {
	if x != nil {
		return x.HostRoutes
	}
	return nil
}

func (x *WorkloadPort) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// Layer2AttachmentRef identifies a Layer2Attachment for an L2 (bridge) attach.
// It is a bare name: Layer2Attachments are only ever read from one namespace
// (the agent's --intent-namespace, mirroring the operator's), which the agent
// stamps onto the recorded attachment.
type Layer2AttachmentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer2AttachmentRef) Reset() {
	*x = Layer2AttachmentRef{}
	mi := &file_workloadcni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer2AttachmentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer2AttachmentRef) ProtoMessage() {}

func (x *Layer2AttachmentRef) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer2AttachmentRef.ProtoReflect.Descriptor instead.
func (*Layer2AttachmentRef) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{1}
}

func (x *Layer2AttachmentRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Layer2TrunkMember is one tagged member of an L2 trunk attachment.
type Layer2TrunkMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ref identifies the Layer2Attachment whose L2 domain the member is bridged
	// into.
	Ref *Layer2AttachmentRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// vlan is the 802.1Q VLAN id the member is tagged with on the workload side.
	// 0 means the L2 domain's own VLAN id, which the agent only learns once the
	// referenced Layer2 is present on the node, so it is resolved there.
	Vlan          uint32 `protobuf:"varint,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer2TrunkMember) Reset() {
	*x = Layer2TrunkMember{}
	mi := &file_workloadcni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer2TrunkMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer2TrunkMember) ProtoMessage() {}

func (x *Layer2TrunkMember) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer2TrunkMember.ProtoReflect.Descriptor instead.
func (*Layer2TrunkMember) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{2}
}

func (x *Layer2TrunkMember) GetRef() *Layer2AttachmentRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Layer2TrunkMember) GetVlan() uint32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_namespace / pod_name identify the owning pod.
	PodNamespace string `protobuf:"bytes,1,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName      string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// container_id is the CNI container ID (sandbox identity).
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// vrf is the target VRF; empty means the underlay/default table.
	// Mutually exclusive with layer2_attachment_ref and layer2_trunk.
	Vrf  string        `protobuf:"bytes,4,opt,name=vrf,proto3" json:"vrf,omitempty"`
	Port *WorkloadPort `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	// layer2_attachment_ref, when set, enslaves the moved interface into the L2
	// bridge of the referenced Layer2Attachment as an untagged access port
	// instead of routing it. The routed fields (vrf, gateways, host_routes) must
	// be empty in L2 mode.
	Layer2AttachmentRef *Layer2AttachmentRef `protobuf:"bytes,6,opt,name=layer2_attachment_ref,json=layer2AttachmentRef,proto3" json:"layer2_attachment_ref,omitempty"`
	// layer2_trunk, when non-empty, makes the moved interface an 802.1Q trunk
	// carrying one tagged member per entry. The interface itself is not bridged,
	// so untagged and unmapped-VLAN frames go nowhere. Mutually exclusive with
	// layer2_attachment_ref and with the routed fields.
	Layer2Trunk   []*Layer2TrunkMember `protobuf:"bytes,7,rep,name=layer2_trunk,json=layer2Trunk,proto3" json:"layer2_trunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_workloadcni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{3}
}

func (x *AddRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *AddRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AddRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AddRequest) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

func (x *AddRequest) GetPort() *WorkloadPort {
	if x != nil {
		return x.Port
	}
	return nil
}

func (x *AddRequest) GetLayer2AttachmentRef() *Layer2AttachmentRef {
	if x != nil {
		return x.Layer2AttachmentRef
	}
	return nil
}

func (x *AddRequest) GetLayer2Trunk() []*Layer2TrunkMember {
	if x != nil {
		return x.Layer2Trunk
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_workloadcni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{4}
}

type DelRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// interface is optional; when set, only the matching attachment is removed.
	Interface     string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_workloadcni_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{5}
}

func (x *DelRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DelRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_workloadcni_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workloadcni_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_workloadcni_proto_rawDescGZIP(), []int{6}
}

var File_workloadcni_proto protoreflect.FileDescriptor

const file_workloadcni_proto_rawDesc = "" +
	"\n" +
	"\x11workloadcni.proto\x12\x0eworkloadcni.v1\"\x9d\x01\n" +
	"\fWorkloadPort\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"gateway_v4\x18\x02 \x01(\tR\tgatewayV4\x12\x1d\n" +
	"\n" +
	"gateway_v6\x18\x03 \x01(\tR\tgatewayV6\x12\x1f\n" +
	"\vhost_routes\x18\x04 \x03(\tR\n" +
	"hostRoutes\x12\x10\n" +
	"\x03mtu\x18\b \x01(\rR\x03mtu\":\n" +
	"\x13Layer2AttachmentRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameJ\x04\b\x02\x10\x03R\tnamespace\"^\n" +
	"\x11Layer2TrunkMember\x125\n" +
	"\x03ref\x18\x01 \x01(\v2#.workloadcni.v1.Layer2AttachmentRefR\x03ref\x12\x12\n" +
	"\x04vlan\x18\x02 \x01(\rR\x04vlan\"\xd2\x02\n" +
	"\n" +
	"AddRequest\x12#\n" +
	"\rpod_namespace\x18\x01 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03vrf\x18\x04 \x01(\tR\x03vrf\x120\n" +
	"\x04port\x18\x05 \x01(\v2\x1c.workloadcni.v1.WorkloadPortR\x04port\x12W\n" +
	"\x15layer2_attachment_ref\x18\x06 \x01(\v2#.workloadcni.v1.Layer2AttachmentRefR\x13layer2AttachmentRef\x12D\n" +
	"\flayer2_trunk\x18\a \x03(\v2!.workloadcni.v1.Layer2TrunkMemberR\vlayer2Trunk\"\r\n" +
	"\vAddResponse\"M\n" +
	"\n" +
	"DelRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\"\r\n" +
	"\vDelResponse2\x8d\x01\n" +
	"\vWorkloadCNI\x12>\n" +
	"\x03Add\x12\x1a.workloadcni.v1.AddRequest\x1a\x1b.workloadcni.v1.AddResponse\x12>\n" +
	"\x03Del\x12\x1a.workloadcni.v1.DelRequest\x1a\x1b.workloadcni.v1.DelResponseBCZAgithub.com/telekom/das-schiff-network-operator/pkg/workloadcni/pbb\x06proto3"

var (
	file_workloadcni_proto_rawDescOnce sync.Once
	file_workloadcni_proto_rawDescData []byte
)

func file_workloadcni_proto_rawDescGZIP() []byte {
	file_workloadcni_proto_rawDescOnce.Do(func() {
		file_workloadcni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workloadcni_proto_rawDesc), len(file_workloadcni_proto_rawDesc)))
	})
	return file_workloadcni_proto_rawDescData
}

var file_workloadcni_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_workloadcni_proto_goTypes = []any{
	(*WorkloadPort)(nil),        // 0: workloadcni.v1.WorkloadPort
	(*Layer2AttachmentRef)(nil), // 1: workloadcni.v1.Layer2AttachmentRef
	(*Layer2TrunkMember)(nil),   // 2: workloadcni.v1.Layer2TrunkMember
	(*AddRequest)(nil),          // 3: workloadcni.v1.AddRequest
	(*AddResponse)(nil),         // 4: workloadcni.v1.AddResponse
	(*DelRequest)(nil),          // 5: workloadcni.v1.DelRequest
	(*DelResponse)(nil),         // 6: workloadcni.v1.DelResponse
}
var file_workloadcni_proto_depIdxs = []int32{
	1, // 0: workloadcni.v1.Layer2TrunkMember.ref:type_name -> workloadcni.v1.Layer2AttachmentRef
	0, // 1: workloadcni.v1.AddRequest.port:type_name -> workloadcni.v1.WorkloadPort
	1, // 2: workloadcni.v1.AddRequest.layer2_attachment_ref:type_name -> workloadcni.v1.Layer2AttachmentRef
	2, // 3: workloadcni.v1.AddRequest.layer2_trunk:type_name -> workloadcni.v1.Layer2TrunkMember
	3, // 4: workloadcni.v1.WorkloadCNI.Add:input_type -> workloadcni.v1.AddRequest
	5, // 5: workloadcni.v1.WorkloadCNI.Del:input_type -> workloadcni.v1.DelRequest
	4, // 6: workloadcni.v1.WorkloadCNI.Add:output_type -> workloadcni.v1.AddResponse
	6, // 7: workloadcni.v1.WorkloadCNI.Del:output_type -> workloadcni.v1.DelResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workloadcni_proto_init() }
func file_workloadcni_proto_init() {
	if File_workloadcni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workloadcni_proto_rawDesc), len(file_workloadcni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workloadcni_proto_goTypes,
		DependencyIndexes: file_workloadcni_proto_depIdxs,
		MessageInfos:      file_workloadcni_proto_msgTypes,
	}.Build()
	File_workloadcni_proto = out.File
	file_workloadcni_proto_goTypes = nil
	file_workloadcni_proto_depIdxs = nil
}
