// Copyright 2025.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: workloadcni.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadCNI_Add_FullMethodName = "/workloadcni.v1.WorkloadCNI/Add"
	WorkloadCNI_Del_FullMethodName = "/workloadcni.v1.WorkloadCNI/Del"
)

// WorkloadCNIClient is the client API for WorkloadCNI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkloadCNI is the node-local API the workload CNI plugin calls, over a unix
// socket, to hand a routed attachment to the CRA agent. The agent persists the
// attachment into the aggregate per-node NodeWorkloadPorts object and reconciles
// it into the CRA (NETCONF for VSR, netlink for FRR).
type WorkloadCNIClient interface {
	// Add records a routed attachment (CNI ADD). It is idempotent: repeating an
	// Add with the same identity upserts the entry.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Del removes a routed attachment (CNI DEL). It is idempotent: removing an
	// unknown attachment succeeds.
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
}

type workloadCNIClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadCNIClient(cc grpc.ClientConnInterface) WorkloadCNIClient {
	return &workloadCNIClient{cc}
}

func (c *workloadCNIClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, WorkloadCNI_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadCNIClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, WorkloadCNI_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadCNIServer is the server API for WorkloadCNI service.
// All implementations must embed UnimplementedWorkloadCNIServer
// for forward compatibility.
//
// WorkloadCNI is the node-local API the workload CNI plugin calls, over a unix
// socket, to hand a routed attachment to the CRA agent. The agent persists the
// attachment into the aggregate per-node NodeWorkloadPorts object and reconciles
// it into the CRA (NETCONF for VSR, netlink for FRR).
type WorkloadCNIServer interface {
	// Add records a routed attachment (CNI ADD). It is idempotent: repeating an
	// Add with the same identity upserts the entry.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Del removes a routed attachment (CNI DEL). It is idempotent: removing an
	// unknown attachment succeeds.
	Del(context.Context, *DelRequest) (*DelResponse, error)
	mustEmbedUnimplementedWorkloadCNIServer()
}

// UnimplementedWorkloadCNIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadCNIServer struct{}

func (UnimplementedWorkloadCNIServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedWorkloadCNIServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedWorkloadCNIServer) mustEmbedUnimplementedWorkloadCNIServer() {}
func (UnimplementedWorkloadCNIServer) testEmbeddedByValue()                     {}

// UnsafeWorkloadCNIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadCNIServer will
// result in compilation errors.
type UnsafeWorkloadCNIServer interface {
	mustEmbedUnimplementedWorkloadCNIServer()
}

func RegisterWorkloadCNIServer(s grpc.ServiceRegistrar, srv WorkloadCNIServer) {
	// If the following call pancis, it indicates UnimplementedWorkloadCNIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadCNI_ServiceDesc, srv)
}

func _WorkloadCNI_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadCNIServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadCNI_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadCNIServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadCNI_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadCNIServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadCNI_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadCNIServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadCNI_ServiceDesc is the grpc.ServiceDesc for WorkloadCNI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadCNI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workloadcni.v1.WorkloadCNI",
	HandlerType: (*WorkloadCNIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _WorkloadCNI_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _WorkloadCNI_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workloadcni.proto",
}
