apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../default
  - ConfigMap_network-operator-base-config_kube-system.yaml
  - DaemonSet_network-operator-cra-frr_kube-system.yaml
  - NetworkAttachmentDefinition_bridge-hbn_kube-system.yaml
patches:
  - path: delete-netplan-agent.yaml
  - path: delete-netplan-configmap.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: network-operator-agent-cra-frr
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: agent-cra-frr
                volumeMounts:
                  - mountPath: /etc/cra/config/base-config.yaml
                    name: base-config
                    subPath: base-config.yaml
            volumes:
              - hostPath:
                  $patch: delete
                configMap:
                  name: network-operator-base-config
                name: base-config
