// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/reconciler (interfaces: NodeReconcilerInterface)

// Package mock_reconciler is a generated GoMock package.
package mock_reconciler

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockNodeReconcilerInterface is a mock of NodeReconcilerInterface interface.
type MockNodeReconcilerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNodeReconcilerInterfaceMockRecorder
}

// MockNodeReconcilerInterfaceMockRecorder is the mock recorder for MockNodeReconcilerInterface.
type MockNodeReconcilerInterfaceMockRecorder struct {
	mock *MockNodeReconcilerInterface
}

// NewMockNodeReconcilerInterface creates a new mock instance.
func NewMockNodeReconcilerInterface(ctrl *gomock.Controller) *MockNodeReconcilerInterface {
	mock := &MockNodeReconcilerInterface{ctrl: ctrl}
	mock.recorder = &MockNodeReconcilerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeReconcilerInterface) EXPECT() *MockNodeReconcilerInterfaceMockRecorder {
	return m.recorder
}

// GetNodes mocks base method.
func (m *MockNodeReconcilerInterface) GetNodes() map[string]*v1.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].(map[string]*v1.Node)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MockNodeReconcilerInterfaceMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MockNodeReconcilerInterface)(nil).GetNodes))
}
