---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - egresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metallb.io
  resources:
  - bgpadvertisements
  - ipaddresspools
  - l2advertisements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network-connector.sylvaproject.org
  resources:
  - announcementpolicies
  - bgppeerings
  - collectors
  - destinations
  - inbounds
  - interfaceconfigs
  - layer2attachments
  - networks
  - outbounds
  - podnetworks
  - trafficmirrors
  - vrfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network-connector.sylvaproject.org
  resources:
  - announcementpolicies/status
  - bgppeerings/status
  - collectors/status
  - destinations/status
  - inbounds/status
  - interfaceconfigs/status
  - layer2attachments/status
  - networks/status
  - outbounds/status
  - podnetworks/status
  - trafficmirrors/status
  - vrfs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network-connector.sylvaproject.org
  resources:
  - inbounds/finalizers
  - interfaceconfigs/finalizers
  - outbounds/finalizers
  verbs:
  - update
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - bgppeerings
  - layer2networkconfigurations
  - networkconfigrevisions
  - nodenetplanconfigs
  - nodenetworkconfigs
  - vrfrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - bgppeerings/finalizers
  - layer2networkconfigurations/finalizers
  - networkconfigrevisions/finalizers
  - nodenetplanconfigs/finalizers
  - nodenetworkconfigs/finalizers
  - vrfrouteconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - bgppeerings/status
  - layer2networkconfigurations/status
  - networkconfigrevisions/status
  - nodenetplanconfigs/status
  - nodenetworkconfigs/status
  - vrfrouteconfigurations/status
  verbs:
  - get
  - patch
  - update
