# permissions for end users to edit routingtables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: routingtable-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: network-operator
    app.kubernetes.io/part-of: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: routingtable-editor-role
rules:
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - routingtables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - routingtables/status
  verbs:
  - get
