# permissions for end users to view vrfrouteconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vrfrouteconfiguration-viewer-role
rules:
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - vrfrouteconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - vrfrouteconfigurations/status
  verbs:
  - get
