# permissions for end users to edit vrfrouteconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vrfrouteconfiguration-editor-role
rules:
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - vrfrouteconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.t-caas.telekom.com
  resources:
  - vrfrouteconfigurations/status
  verbs:
  - get
