name: 'Feature request'
description: 'Submit a feature request for the das-schiff-network-operator.'
title: '[FEATURE] <Write a short and informative title>'
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request. Before creating a new feature request, please make 
        sure to take a few minutes to check the issue tracker for existing feature requests.
        In addition, please first discuss your feature request informally, e.g. in GitHub discussions, before
        you formally submit one.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: >
        Please describe clearly and concisely what the feature is you would like.
        The description should make your motivation clear.
      placeholder: |
        As a [role], I want to [goal], so that [benefit].
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to include.

  - type: textarea
    attributes:
      label: Proposed API changes (if applicable)
      description: |
        If this feature requires API changes, describe them here with example YAML
      render: yaml

  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: |
        A clear and concise description of any alternative solutions or features you have considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I've checked existing issues and documentation
          required: true
        - label: I'm reporting a feature request, not a security vulnerability
          required: true
        - label: I've included all relevant information
          required: true
