// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/reconciler/common (interfaces: ConfigApplier)

// Package mock_common is a generated GoMock package.
package mock_common

import (
	context "context"
	reflect "reflect"

	"github.com/telekom/das-schiff-network-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigApplier is a mock of ConfigApplier interface.
type MockConfigApplier struct {
	ctrl     *gomock.Controller
	recorder *MockConfigApplierMockRecorder
}

// MockConfigApplierMockRecorder is the mock recorder for MockConfigApplier.
type MockConfigApplierMockRecorder struct {
	mock *MockConfigApplier
}

// NewMockConfigApplier creates a new mock instance.
func NewMockConfigApplier(ctrl *gomock.Controller) *MockConfigApplier {
	mock := &MockConfigApplier{ctrl: ctrl}
	mock.recorder = &MockConfigApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigApplier) EXPECT() *MockConfigApplierMockRecorder {
	return m.recorder
}

// ApplyConfig mocks base method.
func (m *MockConfigApplier) ApplyConfig(ctx context.Context, cfg *v1alpha1.NodeNetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyConfig", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyConfig indicates an expected call of ApplyConfig.
func (mr *MockConfigApplierMockRecorder) ApplyConfig(ctx, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyConfig", reflect.TypeOf((*MockConfigApplier)(nil).ApplyConfig), ctx, cfg)
}
