// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/frr/dbus (interfaces: SystemInterface,ConnInterface)

// Package mock_dbus is a generated GoMock package.
package mock_dbus

import (
	context "context"
	reflect "reflect"

	dbus "github.com/telekom/das-schiff-network-operator/pkg/frr/dbus"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemInterface is a mock of SystemInterface interface.
type MockSystemInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSystemInterfaceMockRecorder
}

// MockSystemInterfaceMockRecorder is the mock recorder for MockSystemInterface.
type MockSystemInterfaceMockRecorder struct {
	mock *MockSystemInterface
}

// NewMockSystemInterface creates a new mock instance.
func NewMockSystemInterface(ctrl *gomock.Controller) *MockSystemInterface {
	mock := &MockSystemInterface{ctrl: ctrl}
	mock.recorder = &MockSystemInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemInterface) EXPECT() *MockSystemInterfaceMockRecorder {
	return m.recorder
}

// NewConn mocks base method.
func (m *MockSystemInterface) NewConn(arg0 context.Context) (dbus.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConn", arg0)
	ret0, _ := ret[0].(dbus.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConn indicates an expected call of NewConn.
func (mr *MockSystemInterfaceMockRecorder) NewConn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConn", reflect.TypeOf((*MockSystemInterface)(nil).NewConn), arg0)
}

// MockConnInterface is a mock of ConnInterface interface.
type MockConnInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConnInterfaceMockRecorder
}

// MockConnInterfaceMockRecorder is the mock recorder for MockConnInterface.
type MockConnInterfaceMockRecorder struct {
	mock *MockConnInterface
}

// NewMockConnInterface creates a new mock instance.
func NewMockConnInterface(ctrl *gomock.Controller) *MockConnInterface {
	mock := &MockConnInterface{ctrl: ctrl}
	mock.recorder = &MockConnInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnInterface) EXPECT() *MockConnInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockConnInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnInterface)(nil).Close))
}

// GetUnitPropertiesContext mocks base method.
func (m *MockConnInterface) GetUnitPropertiesContext(arg0 context.Context, arg1 string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitPropertiesContext", arg0, arg1)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitPropertiesContext indicates an expected call of GetUnitPropertiesContext.
func (mr *MockConnInterfaceMockRecorder) GetUnitPropertiesContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitPropertiesContext", reflect.TypeOf((*MockConnInterface)(nil).GetUnitPropertiesContext), arg0, arg1)
}

// ReloadUnitContext mocks base method.
func (m *MockConnInterface) ReloadUnitContext(arg0 context.Context, arg1, arg2 string, arg3 chan<- string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadUnitContext", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReloadUnitContext indicates an expected call of ReloadUnitContext.
func (mr *MockConnInterfaceMockRecorder) ReloadUnitContext(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadUnitContext", reflect.TypeOf((*MockConnInterface)(nil).ReloadUnitContext), arg0, arg1, arg2, arg3)
}
