//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.ModifyRoute != nil {
		in, out := &in.ModifyRoute, &out.ModifyRoute
		*out = new(ModifyRouteAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressFamily) DeepCopyInto(out *AddressFamily) {
	*out = *in
	if in.ExportFilter != nil {
		in, out := &in.ExportFilter, &out.ExportFilter
		*out = new(Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportFilter != nil {
		in, out := &in.ImportFilter, &out.ImportFilter
		*out = new(Filter)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPrefixes != nil {
		in, out := &in.MaxPrefixes, &out.MaxPrefixes
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressFamily.
func (in *AddressFamily) DeepCopy() *AddressFamily {
	if in == nil {
		return nil
	}
	out := new(AddressFamily)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFDProfile) DeepCopyInto(out *BFDProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFDProfile.
func (in *BFDProfile) DeepCopy() *BFDProfile {
	if in == nil {
		return nil
	}
	out := new(BFDProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPCommunityMatcher) DeepCopyInto(out *BGPCommunityMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPCommunityMatcher.
func (in *BGPCommunityMatcher) DeepCopy() *BGPCommunityMatcher {
	if in == nil {
		return nil
	}
	out := new(BGPCommunityMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeer) DeepCopyInto(out *BGPPeer) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.ListenRange != nil {
		in, out := &in.ListenRange, &out.ListenRange
		*out = new(string)
		**out = **in
	}
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(AddressFamily)
		(*in).DeepCopyInto(*out)
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(AddressFamily)
		(*in).DeepCopyInto(*out)
	}
	if in.BFDProfile != nil {
		in, out := &in.BFDProfile, &out.BFDProfile
		*out = new(BFDProfile)
		**out = **in
	}
	if in.HoldTime != nil {
		in, out := &in.HoldTime, &out.HoldTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepaliveTime != nil {
		in, out := &in.KeepaliveTime, &out.KeepaliveTime
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeer.
func (in *BGPPeer) DeepCopy() *BGPPeer {
	if in == nil {
		return nil
	}
	out := new(BGPPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricVRF) DeepCopyInto(out *FabricVRF) {
	*out = *in
	in.VRF.DeepCopyInto(&out.VRF)
	if in.EVPNImportRouteTargets != nil {
		in, out := &in.EVPNImportRouteTargets, &out.EVPNImportRouteTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EVPNExportRouteTargets != nil {
		in, out := &in.EVPNExportRouteTargets, &out.EVPNExportRouteTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EVPNExportFilter != nil {
		in, out := &in.EVPNExportFilter, &out.EVPNExportFilter
		*out = new(Filter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricVRF.
func (in *FabricVRF) DeepCopy() *FabricVRF {
	if in == nil {
		return nil
	}
	out := new(FabricVRF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FilterItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DefaultAction.DeepCopyInto(&out.DefaultAction)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterItem) DeepCopyInto(out *FilterItem) {
	*out = *in
	in.Matcher.DeepCopyInto(&out.Matcher)
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterItem.
func (in *FilterItem) DeepCopy() *FilterItem {
	if in == nil {
		return nil
	}
	out := new(FilterItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IRB) DeepCopyInto(out *IRB) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IRB.
func (in *IRB) DeepCopy() *IRB {
	if in == nil {
		return nil
	}
	out := new(IRB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer2) DeepCopyInto(out *Layer2) {
	*out = *in
	if in.IRB != nil {
		in, out := &in.IRB, &out.IRB
		*out = new(IRB)
		(*in).DeepCopyInto(*out)
	}
	if in.MirrorACLs != nil {
		in, out := &in.MirrorACLs, &out.MirrorACLs
		*out = make([]MirrorACL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer2.
func (in *Layer2) DeepCopy() *Layer2 {
	if in == nil {
		return nil
	}
	out := new(Layer2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer2NetworkConfiguration) DeepCopyInto(out *Layer2NetworkConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer2NetworkConfiguration.
func (in *Layer2NetworkConfiguration) DeepCopy() *Layer2NetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(Layer2NetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Layer2NetworkConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer2NetworkConfigurationList) DeepCopyInto(out *Layer2NetworkConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Layer2NetworkConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer2NetworkConfigurationList.
func (in *Layer2NetworkConfigurationList) DeepCopy() *Layer2NetworkConfigurationList {
	if in == nil {
		return nil
	}
	out := new(Layer2NetworkConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Layer2NetworkConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer2NetworkConfigurationSpec) DeepCopyInto(out *Layer2NetworkConfigurationSpec) {
	*out = *in
	if in.AnycastGateways != nil {
		in, out := &in.AnycastGateways, &out.AnycastGateways
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NeighSuppression != nil {
		in, out := &in.NeighSuppression, &out.NeighSuppression
		*out = new(bool)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer2NetworkConfigurationSpec.
func (in *Layer2NetworkConfigurationSpec) DeepCopy() *Layer2NetworkConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(Layer2NetworkConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Layer2NetworkConfigurationStatus) DeepCopyInto(out *Layer2NetworkConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Layer2NetworkConfigurationStatus.
func (in *Layer2NetworkConfigurationStatus) DeepCopy() *Layer2NetworkConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(Layer2NetworkConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Loopback) DeepCopyInto(out *Loopback) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Loopback.
func (in *Loopback) DeepCopy() *Loopback {
	if in == nil {
		return nil
	}
	out := new(Loopback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Matcher) DeepCopyInto(out *Matcher) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(PrefixMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.BGPCommunity != nil {
		in, out := &in.BGPCommunity, &out.BGPCommunity
		*out = new(BGPCommunityMatcher)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Matcher.
func (in *Matcher) DeepCopy() *Matcher {
	if in == nil {
		return nil
	}
	out := new(Matcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorACL) DeepCopyInto(out *MirrorACL) {
	*out = *in
	in.TrafficMatch.DeepCopyInto(&out.TrafficMatch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorACL.
func (in *MirrorACL) DeepCopy() *MirrorACL {
	if in == nil {
		return nil
	}
	out := new(MirrorACL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyRouteAction) DeepCopyInto(out *ModifyRouteAction) {
	*out = *in
	if in.AddCommunities != nil {
		in, out := &in.AddCommunities, &out.AddCommunities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditiveCommunities != nil {
		in, out := &in.AdditiveCommunities, &out.AdditiveCommunities
		*out = new(bool)
		**out = **in
	}
	if in.RemoveCommunities != nil {
		in, out := &in.RemoveCommunities, &out.RemoveCommunities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoveAllCommunities != nil {
		in, out := &in.RemoveAllCommunities, &out.RemoveAllCommunities
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyRouteAction.
func (in *ModifyRouteAction) DeepCopy() *ModifyRouteAction {
	if in == nil {
		return nil
	}
	out := new(ModifyRouteAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigRevision) DeepCopyInto(out *NetworkConfigRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigRevision.
func (in *NetworkConfigRevision) DeepCopy() *NetworkConfigRevision {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConfigRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigRevisionList) DeepCopyInto(out *NetworkConfigRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkConfigRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigRevisionList.
func (in *NetworkConfigRevisionList) DeepCopy() *NetworkConfigRevisionList {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConfigRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigRevisionSpec) DeepCopyInto(out *NetworkConfigRevisionSpec) {
	*out = *in
	if in.Layer2 != nil {
		in, out := &in.Layer2, &out.Layer2
		*out = make([]Layer2NetworkConfigurationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Vrf != nil {
		in, out := &in.Vrf, &out.Vrf
		*out = make([]VRFRouteConfigurationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigRevisionSpec.
func (in *NetworkConfigRevisionSpec) DeepCopy() *NetworkConfigRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigRevisionStatus) DeepCopyInto(out *NetworkConfigRevisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigRevisionStatus.
func (in *NetworkConfigRevisionStatus) DeepCopy() *NetworkConfigRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextHop) DeepCopyInto(out *NextHop) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Vrf != nil {
		in, out := &in.Vrf, &out.Vrf
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextHop.
func (in *NextHop) DeepCopy() *NextHop {
	if in == nil {
		return nil
	}
	out := new(NextHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetplanConfig) DeepCopyInto(out *NodeNetplanConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetplanConfig.
func (in *NodeNetplanConfig) DeepCopy() *NodeNetplanConfig {
	if in == nil {
		return nil
	}
	out := new(NodeNetplanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetplanConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetplanConfigList) DeepCopyInto(out *NodeNetplanConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeNetplanConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetplanConfigList.
func (in *NodeNetplanConfigList) DeepCopy() *NodeNetplanConfigList {
	if in == nil {
		return nil
	}
	out := new(NodeNetplanConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetplanConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetplanConfigSpec) DeepCopyInto(out *NodeNetplanConfigSpec) {
	*out = *in
	in.DesiredState.DeepCopyInto(&out.DesiredState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetplanConfigSpec.
func (in *NodeNetplanConfigSpec) DeepCopy() *NodeNetplanConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NodeNetplanConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetplanConfigStatus) DeepCopyInto(out *NodeNetplanConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetplanConfigStatus.
func (in *NodeNetplanConfigStatus) DeepCopy() *NodeNetplanConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetplanConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfig) DeepCopyInto(out *NodeNetworkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfig.
func (in *NodeNetworkConfig) DeepCopy() *NodeNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetworkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigList) DeepCopyInto(out *NodeNetworkConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeNetworkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigList.
func (in *NodeNetworkConfigList) DeepCopy() *NodeNetworkConfigList {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetworkConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigSpec) DeepCopyInto(out *NodeNetworkConfigSpec) {
	*out = *in
	if in.Layer2s != nil {
		in, out := &in.Layer2s, &out.Layer2s
		*out = make(map[string]Layer2, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DefaultVRF != nil {
		in, out := &in.DefaultVRF, &out.DefaultVRF
		*out = new(VRF)
		(*in).DeepCopyInto(*out)
	}
	if in.FabricVRFs != nil {
		in, out := &in.FabricVRFs, &out.FabricVRFs
		*out = make(map[string]FabricVRF, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.LocalVRFs != nil {
		in, out := &in.LocalVRFs, &out.LocalVRFs
		*out = make(map[string]VRF, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigSpec.
func (in *NodeNetworkConfigSpec) DeepCopy() *NodeNetworkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigStatus) DeepCopyInto(out *NodeNetworkConfigStatus) {
	*out = *in
	in.LastUpdate.DeepCopyInto(&out.LastUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigStatus.
func (in *NodeNetworkConfigStatus) DeepCopy() *NodeNetworkConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRoute) DeepCopyInto(out *PolicyRoute) {
	*out = *in
	in.TrafficMatch.DeepCopyInto(&out.TrafficMatch)
	in.NextHop.DeepCopyInto(&out.NextHop)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRoute.
func (in *PolicyRoute) DeepCopy() *PolicyRoute {
	if in == nil {
		return nil
	}
	out := new(PolicyRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixMatcher) DeepCopyInto(out *PrefixMatcher) {
	*out = *in
	if in.Ge != nil {
		in, out := &in.Ge, &out.Ge
		*out = new(int)
		**out = **in
	}
	if in.Le != nil {
		in, out := &in.Le, &out.Le
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixMatcher.
func (in *PrefixMatcher) DeepCopy() *PrefixMatcher {
	if in == nil {
		return nil
	}
	out := new(PrefixMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticRoute) DeepCopyInto(out *StaticRoute) {
	*out = *in
	if in.NextHop != nil {
		in, out := &in.NextHop, &out.NextHop
		*out = new(NextHop)
		(*in).DeepCopyInto(*out)
	}
	if in.BFDProfile != nil {
		in, out := &in.BFDProfile, &out.BFDProfile
		*out = new(BFDProfile)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticRoute.
func (in *StaticRoute) DeepCopy() *StaticRoute {
	if in == nil {
		return nil
	}
	out := new(StaticRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficMatch) DeepCopyInto(out *TrafficMatch) {
	*out = *in
	if in.SrcPrefix != nil {
		in, out := &in.SrcPrefix, &out.SrcPrefix
		*out = new(string)
		**out = **in
	}
	if in.DstPrefix != nil {
		in, out := &in.DstPrefix, &out.DstPrefix
		*out = new(string)
		**out = **in
	}
	if in.SrcPort != nil {
		in, out := &in.SrcPort, &out.SrcPort
		*out = new(uint16)
		**out = **in
	}
	if in.DstPort != nil {
		in, out := &in.DstPort, &out.DstPort
		*out = new(uint16)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficMatch.
func (in *TrafficMatch) DeepCopy() *TrafficMatch {
	if in == nil {
		return nil
	}
	out := new(TrafficMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRF) DeepCopyInto(out *VRF) {
	*out = *in
	if in.Loopbacks != nil {
		in, out := &in.Loopbacks, &out.Loopbacks
		*out = make(map[string]Loopback, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.BGPPeers != nil {
		in, out := &in.BGPPeers, &out.BGPPeers
		*out = make([]BGPPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VRFImports != nil {
		in, out := &in.VRFImports, &out.VRFImports
		*out = make([]VRFImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StaticRoutes != nil {
		in, out := &in.StaticRoutes, &out.StaticRoutes
		*out = make([]StaticRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyRoutes != nil {
		in, out := &in.PolicyRoutes, &out.PolicyRoutes
		*out = make([]PolicyRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MirrorACLs != nil {
		in, out := &in.MirrorACLs, &out.MirrorACLs
		*out = make([]MirrorACL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRF.
func (in *VRF) DeepCopy() *VRF {
	if in == nil {
		return nil
	}
	out := new(VRF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFImport) DeepCopyInto(out *VRFImport) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFImport.
func (in *VRFImport) DeepCopy() *VRFImport {
	if in == nil {
		return nil
	}
	out := new(VRFImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFRouteConfiguration) DeepCopyInto(out *VRFRouteConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFRouteConfiguration.
func (in *VRFRouteConfiguration) DeepCopy() *VRFRouteConfiguration {
	if in == nil {
		return nil
	}
	out := new(VRFRouteConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VRFRouteConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFRouteConfigurationList) DeepCopyInto(out *VRFRouteConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VRFRouteConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFRouteConfigurationList.
func (in *VRFRouteConfigurationList) DeepCopy() *VRFRouteConfigurationList {
	if in == nil {
		return nil
	}
	out := new(VRFRouteConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VRFRouteConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFRouteConfigurationSpec) DeepCopyInto(out *VRFRouteConfigurationSpec) {
	*out = *in
	if in.RouteTarget != nil {
		in, out := &in.RouteTarget, &out.RouteTarget
		*out = new(string)
		**out = **in
	}
	if in.VNI != nil {
		in, out := &in.VNI, &out.VNI
		*out = new(int)
		**out = **in
	}
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = make([]VrfRouteConfigurationPrefixItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Export != nil {
		in, out := &in.Export, &out.Export
		*out = make([]VrfRouteConfigurationPrefixItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Community != nil {
		in, out := &in.Community, &out.Community
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFRouteConfigurationSpec.
func (in *VRFRouteConfigurationSpec) DeepCopy() *VRFRouteConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(VRFRouteConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRFRouteConfigurationStatus) DeepCopyInto(out *VRFRouteConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRFRouteConfigurationStatus.
func (in *VRFRouteConfigurationStatus) DeepCopy() *VRFRouteConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(VRFRouteConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfRouteConfigurationPrefixItem) DeepCopyInto(out *VrfRouteConfigurationPrefixItem) {
	*out = *in
	if in.GE != nil {
		in, out := &in.GE, &out.GE
		*out = new(int)
		**out = **in
	}
	if in.LE != nil {
		in, out := &in.LE, &out.LE
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfRouteConfigurationPrefixItem.
func (in *VrfRouteConfigurationPrefixItem) DeepCopy() *VrfRouteConfigurationPrefixItem {
	if in == nil {
		return nil
	}
	out := new(VrfRouteConfigurationPrefixItem)
	in.DeepCopyInto(out)
	return out
}
