// Copyright 2025.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: routedcni.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutedCNI_Add_FullMethodName = "/routedcni.v1.RoutedCNI/Add"
	RoutedCNI_Del_FullMethodName = "/routedcni.v1.RoutedCNI/Del"
)

// RoutedCNIClient is the client API for RoutedCNI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoutedCNI is the node-local API the routed CNI plugin calls, over a unix
// socket, to hand a routed attachment to the CRA agent. The agent persists the
// attachment into the aggregate per-node NodeRoutedPorts object and reconciles
// it into the CRA (NETCONF for VSR, netlink for FRR).
type RoutedCNIClient interface {
	// Add records a routed attachment (CNI ADD). It is idempotent: repeating an
	// Add with the same identity upserts the entry.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Del removes a routed attachment (CNI DEL). It is idempotent: removing an
	// unknown attachment succeeds.
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
}

type routedCNIClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutedCNIClient(cc grpc.ClientConnInterface) RoutedCNIClient {
	return &routedCNIClient{cc}
}

func (c *routedCNIClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, RoutedCNI_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routedCNIClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, RoutedCNI_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutedCNIServer is the server API for RoutedCNI service.
// All implementations must embed UnimplementedRoutedCNIServer
// for forward compatibility.
//
// RoutedCNI is the node-local API the routed CNI plugin calls, over a unix
// socket, to hand a routed attachment to the CRA agent. The agent persists the
// attachment into the aggregate per-node NodeRoutedPorts object and reconciles
// it into the CRA (NETCONF for VSR, netlink for FRR).
type RoutedCNIServer interface {
	// Add records a routed attachment (CNI ADD). It is idempotent: repeating an
	// Add with the same identity upserts the entry.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Del removes a routed attachment (CNI DEL). It is idempotent: removing an
	// unknown attachment succeeds.
	Del(context.Context, *DelRequest) (*DelResponse, error)
	mustEmbedUnimplementedRoutedCNIServer()
}

// UnimplementedRoutedCNIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutedCNIServer struct{}

func (UnimplementedRoutedCNIServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedRoutedCNIServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedRoutedCNIServer) mustEmbedUnimplementedRoutedCNIServer() {}
func (UnimplementedRoutedCNIServer) testEmbeddedByValue()                   {}

// UnsafeRoutedCNIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutedCNIServer will
// result in compilation errors.
type UnsafeRoutedCNIServer interface {
	mustEmbedUnimplementedRoutedCNIServer()
}

func RegisterRoutedCNIServer(s grpc.ServiceRegistrar, srv RoutedCNIServer) {
	// If the following call pancis, it indicates UnimplementedRoutedCNIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutedCNI_ServiceDesc, srv)
}

func _RoutedCNI_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutedCNIServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutedCNI_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutedCNIServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutedCNI_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutedCNIServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutedCNI_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutedCNIServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutedCNI_ServiceDesc is the grpc.ServiceDesc for RoutedCNI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutedCNI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routedcni.v1.RoutedCNI",
	HandlerType: (*RoutedCNIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RoutedCNI_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _RoutedCNI_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routedcni.proto",
}
