// Copyright 2025.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: routedcni.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoutedPort is the datapath payload for a routed attachment.
type RoutedPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface is the moved interface name inside the CRA network namespace.
	// VSR references it as infra-<interface>.
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// gateway_v4 is the on-link IPv4 gateway address (with prefix length).
	GatewayV4 string `protobuf:"bytes,2,opt,name=gateway_v4,json=gatewayV4,proto3" json:"gateway_v4,omitempty"`
	// gateway_v6 is the on-link IPv6 gateway address (with prefix length).
	GatewayV6 string `protobuf:"bytes,3,opt,name=gateway_v6,json=gatewayV6,proto3" json:"gateway_v6,omitempty"`
	// host_routes are the workload host addresses (/32, /128) reachable via the
	// interface.
	HostRoutes    []string `protobuf:"bytes,4,rep,name=host_routes,json=hostRoutes,proto3" json:"host_routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutedPort) Reset() {
	*x = RoutedPort{}
	mi := &file_routedcni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedPort) ProtoMessage() {}

func (x *RoutedPort) ProtoReflect() protoreflect.Message {
	mi := &file_routedcni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedPort.ProtoReflect.Descriptor instead.
func (*RoutedPort) Descriptor() ([]byte, []int) {
	return file_routedcni_proto_rawDescGZIP(), []int{0}
}

func (x *RoutedPort) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *RoutedPort) GetGatewayV4() string {
	if x != nil {
		return x.GatewayV4
	}
	return ""
}

func (x *RoutedPort) GetGatewayV6() string {
	if x != nil {
		return x.GatewayV6
	}
	return ""
}

func (x *RoutedPort) GetHostRoutes() []string {
	if x != nil {
		return x.HostRoutes
	}
	return nil
}

type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_namespace / pod_name identify the owning pod.
	PodNamespace string `protobuf:"bytes,1,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName      string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// container_id is the CNI container ID (sandbox identity).
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// vrf is the target VRF; empty means the underlay/default table.
	Vrf           string      `protobuf:"bytes,4,opt,name=vrf,proto3" json:"vrf,omitempty"`
	Port          *RoutedPort `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_routedcni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routedcni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_routedcni_proto_rawDescGZIP(), []int{1}
}

func (x *AddRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *AddRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AddRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AddRequest) GetVrf() string {
	if x != nil {
		return x.Vrf
	}
	return ""
}

func (x *AddRequest) GetPort() *RoutedPort {
	if x != nil {
		return x.Port
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_routedcni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routedcni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_routedcni_proto_rawDescGZIP(), []int{2}
}

type DelRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// interface is optional; when set, only the matching attachment is removed.
	Interface     string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_routedcni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routedcni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_routedcni_proto_rawDescGZIP(), []int{3}
}

func (x *DelRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DelRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_routedcni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routedcni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_routedcni_proto_rawDescGZIP(), []int{4}
}

var File_routedcni_proto protoreflect.FileDescriptor

const file_routedcni_proto_rawDesc = "" +
	"\n" +
	"\x0froutedcni.proto\x12\froutedcni.v1\"\x89\x01\n" +
	"\n" +
	"RoutedPort\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"gateway_v4\x18\x02 \x01(\tR\tgatewayV4\x12\x1d\n" +
	"\n" +
	"gateway_v6\x18\x03 \x01(\tR\tgatewayV6\x12\x1f\n" +
	"\vhost_routes\x18\x04 \x03(\tR\n" +
	"hostRoutes\"\xaf\x01\n" +
	"\n" +
	"AddRequest\x12#\n" +
	"\rpod_namespace\x18\x01 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03vrf\x18\x04 \x01(\tR\x03vrf\x12,\n" +
	"\x04port\x18\x05 \x01(\v2\x18.routedcni.v1.RoutedPortR\x04port\"\r\n" +
	"\vAddResponse\"M\n" +
	"\n" +
	"DelRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\"\r\n" +
	"\vDelResponse2\x83\x01\n" +
	"\tRoutedCNI\x12:\n" +
	"\x03Add\x12\x18.routedcni.v1.AddRequest\x1a\x19.routedcni.v1.AddResponse\x12:\n" +
	"\x03Del\x12\x18.routedcni.v1.DelRequest\x1a\x19.routedcni.v1.DelResponseBAZ?github.com/telekom/das-schiff-network-operator/pkg/routedcni/pbb\x06proto3"

var (
	file_routedcni_proto_rawDescOnce sync.Once
	file_routedcni_proto_rawDescData []byte
)

func file_routedcni_proto_rawDescGZIP() []byte {
	file_routedcni_proto_rawDescOnce.Do(func() {
		file_routedcni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routedcni_proto_rawDesc), len(file_routedcni_proto_rawDesc)))
	})
	return file_routedcni_proto_rawDescData
}

var file_routedcni_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_routedcni_proto_goTypes = []any{
	(*RoutedPort)(nil),  // 0: routedcni.v1.RoutedPort
	(*AddRequest)(nil),  // 1: routedcni.v1.AddRequest
	(*AddResponse)(nil), // 2: routedcni.v1.AddResponse
	(*DelRequest)(nil),  // 3: routedcni.v1.DelRequest
	(*DelResponse)(nil), // 4: routedcni.v1.DelResponse
}
var file_routedcni_proto_depIdxs = []int32{
	0, // 0: routedcni.v1.AddRequest.port:type_name -> routedcni.v1.RoutedPort
	1, // 1: routedcni.v1.RoutedCNI.Add:input_type -> routedcni.v1.AddRequest
	3, // 2: routedcni.v1.RoutedCNI.Del:input_type -> routedcni.v1.DelRequest
	2, // 3: routedcni.v1.RoutedCNI.Add:output_type -> routedcni.v1.AddResponse
	4, // 4: routedcni.v1.RoutedCNI.Del:output_type -> routedcni.v1.DelResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_routedcni_proto_init() }
func file_routedcni_proto_init() {
	if File_routedcni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routedcni_proto_rawDesc), len(file_routedcni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routedcni_proto_goTypes,
		DependencyIndexes: file_routedcni_proto_depIdxs,
		MessageInfos:      file_routedcni_proto_msgTypes,
	}.Build()
	File_routedcni_proto = out.File
	file_routedcni_proto_goTypes = nil
	file_routedcni_proto_depIdxs = nil
}
