apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-sync
  namespace: system
  labels:
    app.kubernetes.io/component: network-sync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: network-operator
      app.kubernetes.io/component: network-sync
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: network-sync
      labels:
        app.kubernetes.io/name: network-operator
        app.kubernetes.io/component: network-sync
    spec:
      serviceAccountName: network-sync
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
          operator: Exists
      containers:
        - name: network-sync
          image: ghcr.io/telekom/das-schiff-network-sync:latest
          imagePullPolicy: IfNotPresent
          command:
            - /network-sync
          args:
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
            - --remote-namespace=default
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
