frr version 10.3.1
frr defaults datacenter
hostname leaf2
log syslog informational
service integrated-vtysh-config

router bgp 65500
 bgp router-id 192.0.2.11
 no bgp ebgp-requires-policy
 !
 neighbor eth-dcgw1 interface remote-as 64497
 neighbor eth-dcgw2 interface remote-as 64497
 !
 neighbor server peer-group
 neighbor server remote-as 65501
 neighbor server bfd
 neighbor server timers 1 3
 !
 neighbor eth-srv1 interface peer-group server
 neighbor eth-srv2 interface peer-group server
 neighbor eth-srv3 interface peer-group server
 neighbor eth-srv4 interface peer-group server
