// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/nl (interfaces: NetlinkToolkitInterface)

// Package mock_nl is a generated GoMock package.
package mock_nl

import (
	net "net"
	reflect "reflect"

	netlink "github.com/vishvananda/netlink"
	nl "github.com/vishvananda/netlink/nl"
	gomock "go.uber.org/mock/gomock"
)

// MockNetlinkToolkitInterface is a mock of NetlinkToolkitInterface interface.
type MockNetlinkToolkitInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNetlinkToolkitInterfaceMockRecorder
}

// MockNetlinkToolkitInterfaceMockRecorder is the mock recorder for MockNetlinkToolkitInterface.
type MockNetlinkToolkitInterfaceMockRecorder struct {
	mock *MockNetlinkToolkitInterface
}

// NewMockNetlinkToolkitInterface creates a new mock instance.
func NewMockNetlinkToolkitInterface(ctrl *gomock.Controller) *MockNetlinkToolkitInterface {
	mock := &MockNetlinkToolkitInterface{ctrl: ctrl}
	mock.recorder = &MockNetlinkToolkitInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetlinkToolkitInterface) EXPECT() *MockNetlinkToolkitInterfaceMockRecorder {
	return m.recorder
}

// AddrAdd mocks base method.
func (m *MockNetlinkToolkitInterface) AddrAdd(arg0 netlink.Link, arg1 *netlink.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrAdd", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddrAdd indicates an expected call of AddrAdd.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) AddrAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrAdd", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).AddrAdd), arg0, arg1)
}

// AddrDel mocks base method.
func (m *MockNetlinkToolkitInterface) AddrDel(arg0 netlink.Link, arg1 *netlink.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrDel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddrDel indicates an expected call of AddrDel.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) AddrDel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrDel", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).AddrDel), arg0, arg1)
}

// AddrList mocks base method.
func (m *MockNetlinkToolkitInterface) AddrList(arg0 netlink.Link, arg1 int) ([]netlink.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrList", arg0, arg1)
	ret0, _ := ret[0].([]netlink.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddrList indicates an expected call of AddrList.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) AddrList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrList", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).AddrList), arg0, arg1)
}

// ExecuteNetlinkRequest mocks base method.
func (m *MockNetlinkToolkitInterface) ExecuteNetlinkRequest(arg0 *nl.NetlinkRequest, arg1 int, arg2 uint16) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteNetlinkRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteNetlinkRequest indicates an expected call of ExecuteNetlinkRequest.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) ExecuteNetlinkRequest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteNetlinkRequest", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).ExecuteNetlinkRequest), arg0, arg1, arg2)
}

// LinkAdd mocks base method.
func (m *MockNetlinkToolkitInterface) LinkAdd(arg0 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAdd", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAdd indicates an expected call of LinkAdd.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkAdd(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAdd", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkAdd), arg0)
}

// LinkByIndex mocks base method.
func (m *MockNetlinkToolkitInterface) LinkByIndex(arg0 int) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByIndex", arg0)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByIndex indicates an expected call of LinkByIndex.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkByIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByIndex", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkByIndex), arg0)
}

// LinkByName mocks base method.
func (m *MockNetlinkToolkitInterface) LinkByName(arg0 string) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByName", arg0)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByName", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkByName), arg0)
}

// LinkDel mocks base method.
func (m *MockNetlinkToolkitInterface) LinkDel(arg0 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkDel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkDel indicates an expected call of LinkDel.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkDel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkDel", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkDel), arg0)
}

// LinkGetProtinfo mocks base method.
func (m *MockNetlinkToolkitInterface) LinkGetProtinfo(arg0 netlink.Link) (netlink.Protinfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkGetProtinfo", arg0)
	ret0, _ := ret[0].(netlink.Protinfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkGetProtinfo indicates an expected call of LinkGetProtinfo.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkGetProtinfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkGetProtinfo", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkGetProtinfo), arg0)
}

// LinkList mocks base method.
func (m *MockNetlinkToolkitInterface) LinkList() ([]netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkList")
	ret0, _ := ret[0].([]netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkList indicates an expected call of LinkList.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkList", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkList))
}

// LinkSetDown mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetDown(arg0 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetDown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetDown indicates an expected call of LinkSetDown.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetDown(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetDown", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetDown), arg0)
}

// LinkSetHairpin mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetHairpin(arg0 netlink.Link, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetHairpin", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetHairpin indicates an expected call of LinkSetHairpin.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetHairpin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetHairpin", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetHairpin), arg0, arg1)
}

// LinkSetHardwareAddr mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetHardwareAddr(arg0 netlink.Link, arg1 net.HardwareAddr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetHardwareAddr", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetHardwareAddr indicates an expected call of LinkSetHardwareAddr.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetHardwareAddr(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetHardwareAddr", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetHardwareAddr), arg0, arg1)
}

// LinkSetLearning mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetLearning(arg0 netlink.Link, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetLearning", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetLearning indicates an expected call of LinkSetLearning.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetLearning(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetLearning", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetLearning), arg0, arg1)
}

// LinkSetMTU mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetMTU(arg0 netlink.Link, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMTU", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMTU indicates an expected call of LinkSetMTU.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetMTU(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMTU", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetMTU), arg0, arg1)
}

// LinkSetMaster mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetMaster(arg0, arg1 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMaster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMaster indicates an expected call of LinkSetMaster.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetMaster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMaster", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetMaster), arg0, arg1)
}

// LinkSetMasterByIndex mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetMasterByIndex(arg0 netlink.Link, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMasterByIndex", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMasterByIndex indicates an expected call of LinkSetMasterByIndex.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetMasterByIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMasterByIndex", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetMasterByIndex), arg0, arg1)
}

// LinkSetNoMaster mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetNoMaster(arg0 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetNoMaster", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetNoMaster indicates an expected call of LinkSetNoMaster.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetNoMaster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetNoMaster", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetNoMaster), arg0)
}

// LinkSetUp mocks base method.
func (m *MockNetlinkToolkitInterface) LinkSetUp(arg0 netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetUp", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetUp indicates an expected call of LinkSetUp.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) LinkSetUp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetUp", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).LinkSetUp), arg0)
}

// NeighList mocks base method.
func (m *MockNetlinkToolkitInterface) NeighList(arg0, arg1 int) ([]netlink.Neigh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeighList", arg0, arg1)
	ret0, _ := ret[0].([]netlink.Neigh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeighList indicates an expected call of NeighList.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) NeighList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeighList", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).NeighList), arg0, arg1)
}

// NewIPNet mocks base method.
func (m *MockNetlinkToolkitInterface) NewIPNet(arg0 net.IP) *net.IPNet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIPNet", arg0)
	ret0, _ := ret[0].(*net.IPNet)
	return ret0
}

// NewIPNet indicates an expected call of NewIPNet.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) NewIPNet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIPNet", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).NewIPNet), arg0)
}

// ParseAddr mocks base method.
func (m *MockNetlinkToolkitInterface) ParseAddr(arg0 string) (*netlink.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAddr", arg0)
	ret0, _ := ret[0].(*netlink.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAddr indicates an expected call of ParseAddr.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) ParseAddr(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAddr", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).ParseAddr), arg0)
}

// RouteAdd mocks base method.
func (m *MockNetlinkToolkitInterface) RouteAdd(arg0 *netlink.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteAdd", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RouteAdd indicates an expected call of RouteAdd.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) RouteAdd(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteAdd", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).RouteAdd), arg0)
}

// RouteDel mocks base method.
func (m *MockNetlinkToolkitInterface) RouteDel(arg0 *netlink.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteDel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RouteDel indicates an expected call of RouteDel.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) RouteDel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteDel", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).RouteDel), arg0)
}

// RouteListFiltered mocks base method.
func (m *MockNetlinkToolkitInterface) RouteListFiltered(arg0 int, arg1 *netlink.Route, arg2 uint64) ([]netlink.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteListFiltered", arg0, arg1, arg2)
	ret0, _ := ret[0].([]netlink.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteListFiltered indicates an expected call of RouteListFiltered.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) RouteListFiltered(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteListFiltered", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).RouteListFiltered), arg0, arg1, arg2)
}

// VethPeerIndex mocks base method.
func (m *MockNetlinkToolkitInterface) VethPeerIndex(arg0 *netlink.Veth) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VethPeerIndex", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VethPeerIndex indicates an expected call of VethPeerIndex.
func (mr *MockNetlinkToolkitInterfaceMockRecorder) VethPeerIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VethPeerIndex", reflect.TypeOf((*MockNetlinkToolkitInterface)(nil).VethPeerIndex), arg0)
}
