// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/nl (interfaces: ToolkitInterface)
//
// Generated by this command:
//
//	mockgen -destination ./mock/mock_nl.go . ToolkitInterface
//

// Package mock_nl is a generated GoMock package.
package mock_nl

import (
	net "net"
	reflect "reflect"

	netlink "github.com/vishvananda/netlink"
	nl "github.com/vishvananda/netlink/nl"
	gomock "go.uber.org/mock/gomock"
)

// MockToolkitInterface is a mock of ToolkitInterface interface.
type MockToolkitInterface struct {
	ctrl     *gomock.Controller
	recorder *MockToolkitInterfaceMockRecorder
	isgomock struct{}
}

// MockToolkitInterfaceMockRecorder is the mock recorder for MockToolkitInterface.
type MockToolkitInterfaceMockRecorder struct {
	mock *MockToolkitInterface
}

// NewMockToolkitInterface creates a new mock instance.
func NewMockToolkitInterface(ctrl *gomock.Controller) *MockToolkitInterface {
	mock := &MockToolkitInterface{ctrl: ctrl}
	mock.recorder = &MockToolkitInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolkitInterface) EXPECT() *MockToolkitInterfaceMockRecorder {
	return m.recorder
}

// AddrAdd mocks base method.
func (m *MockToolkitInterface) AddrAdd(link netlink.Link, addr *netlink.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrAdd", link, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddrAdd indicates an expected call of AddrAdd.
func (mr *MockToolkitInterfaceMockRecorder) AddrAdd(link, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrAdd", reflect.TypeOf((*MockToolkitInterface)(nil).AddrAdd), link, addr)
}

// AddrDel mocks base method.
func (m *MockToolkitInterface) AddrDel(link netlink.Link, addr *netlink.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrDel", link, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddrDel indicates an expected call of AddrDel.
func (mr *MockToolkitInterfaceMockRecorder) AddrDel(link, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrDel", reflect.TypeOf((*MockToolkitInterface)(nil).AddrDel), link, addr)
}

// AddrList mocks base method.
func (m *MockToolkitInterface) AddrList(link netlink.Link, family int) ([]netlink.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrList", link, family)
	ret0, _ := ret[0].([]netlink.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddrList indicates an expected call of AddrList.
func (mr *MockToolkitInterfaceMockRecorder) AddrList(link, family any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrList", reflect.TypeOf((*MockToolkitInterface)(nil).AddrList), link, family)
}

// AddrReplace mocks base method.
func (m *MockToolkitInterface) AddrReplace(link netlink.Link, addr *netlink.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddrReplace", link, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddrReplace indicates an expected call of AddrReplace.
func (mr *MockToolkitInterfaceMockRecorder) AddrReplace(link, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddrReplace", reflect.TypeOf((*MockToolkitInterface)(nil).AddrReplace), link, addr)
}

// ExecuteNetlinkRequest mocks base method.
func (m *MockToolkitInterface) ExecuteNetlinkRequest(req *nl.NetlinkRequest, sockType int, resType uint16) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteNetlinkRequest", req, sockType, resType)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteNetlinkRequest indicates an expected call of ExecuteNetlinkRequest.
func (mr *MockToolkitInterfaceMockRecorder) ExecuteNetlinkRequest(req, sockType, resType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteNetlinkRequest", reflect.TypeOf((*MockToolkitInterface)(nil).ExecuteNetlinkRequest), req, sockType, resType)
}

// LinkAdd mocks base method.
func (m *MockToolkitInterface) LinkAdd(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAdd", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAdd indicates an expected call of LinkAdd.
func (mr *MockToolkitInterfaceMockRecorder) LinkAdd(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAdd", reflect.TypeOf((*MockToolkitInterface)(nil).LinkAdd), link)
}

// LinkByIndex mocks base method.
func (m *MockToolkitInterface) LinkByIndex(index int) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByIndex", index)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByIndex indicates an expected call of LinkByIndex.
func (mr *MockToolkitInterfaceMockRecorder) LinkByIndex(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByIndex", reflect.TypeOf((*MockToolkitInterface)(nil).LinkByIndex), index)
}

// LinkByName mocks base method.
func (m *MockToolkitInterface) LinkByName(name string) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByName", name)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockToolkitInterfaceMockRecorder) LinkByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByName", reflect.TypeOf((*MockToolkitInterface)(nil).LinkByName), name)
}

// LinkDel mocks base method.
func (m *MockToolkitInterface) LinkDel(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkDel", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkDel indicates an expected call of LinkDel.
func (mr *MockToolkitInterfaceMockRecorder) LinkDel(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkDel", reflect.TypeOf((*MockToolkitInterface)(nil).LinkDel), link)
}

// LinkGetProtinfo mocks base method.
func (m *MockToolkitInterface) LinkGetProtinfo(link netlink.Link) (netlink.Protinfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkGetProtinfo", link)
	ret0, _ := ret[0].(netlink.Protinfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkGetProtinfo indicates an expected call of LinkGetProtinfo.
func (mr *MockToolkitInterfaceMockRecorder) LinkGetProtinfo(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkGetProtinfo", reflect.TypeOf((*MockToolkitInterface)(nil).LinkGetProtinfo), link)
}

// LinkList mocks base method.
func (m *MockToolkitInterface) LinkList() ([]netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkList")
	ret0, _ := ret[0].([]netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkList indicates an expected call of LinkList.
func (mr *MockToolkitInterfaceMockRecorder) LinkList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkList", reflect.TypeOf((*MockToolkitInterface)(nil).LinkList))
}

// LinkSetDown mocks base method.
func (m *MockToolkitInterface) LinkSetDown(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetDown", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetDown indicates an expected call of LinkSetDown.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetDown(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetDown", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetDown), link)
}

// LinkSetHairpin mocks base method.
func (m *MockToolkitInterface) LinkSetHairpin(link netlink.Link, mode bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetHairpin", link, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetHairpin indicates an expected call of LinkSetHairpin.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetHairpin(link, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetHairpin", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetHairpin), link, mode)
}

// LinkSetHardwareAddr mocks base method.
func (m *MockToolkitInterface) LinkSetHardwareAddr(link netlink.Link, hwaddr net.HardwareAddr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetHardwareAddr", link, hwaddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetHardwareAddr indicates an expected call of LinkSetHardwareAddr.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetHardwareAddr(link, hwaddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetHardwareAddr", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetHardwareAddr), link, hwaddr)
}

// LinkSetLearning mocks base method.
func (m *MockToolkitInterface) LinkSetLearning(link netlink.Link, mode bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetLearning", link, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetLearning indicates an expected call of LinkSetLearning.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetLearning(link, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetLearning", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetLearning), link, mode)
}

// LinkSetMTU mocks base method.
func (m *MockToolkitInterface) LinkSetMTU(link netlink.Link, mtu int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMTU", link, mtu)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMTU indicates an expected call of LinkSetMTU.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetMTU(link, mtu any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMTU", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetMTU), link, mtu)
}

// LinkSetMaster mocks base method.
func (m *MockToolkitInterface) LinkSetMaster(link, master netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMaster", link, master)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMaster indicates an expected call of LinkSetMaster.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetMaster(link, master any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMaster", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetMaster), link, master)
}

// LinkSetMasterByIndex mocks base method.
func (m *MockToolkitInterface) LinkSetMasterByIndex(link netlink.Link, masterIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetMasterByIndex", link, masterIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetMasterByIndex indicates an expected call of LinkSetMasterByIndex.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetMasterByIndex(link, masterIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetMasterByIndex", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetMasterByIndex), link, masterIndex)
}

// LinkSetNoMaster mocks base method.
func (m *MockToolkitInterface) LinkSetNoMaster(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetNoMaster", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetNoMaster indicates an expected call of LinkSetNoMaster.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetNoMaster(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetNoMaster", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetNoMaster), link)
}

// LinkSetUp mocks base method.
func (m *MockToolkitInterface) LinkSetUp(link netlink.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSetUp", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSetUp indicates an expected call of LinkSetUp.
func (mr *MockToolkitInterfaceMockRecorder) LinkSetUp(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSetUp", reflect.TypeOf((*MockToolkitInterface)(nil).LinkSetUp), link)
}

// NeighList mocks base method.
func (m *MockToolkitInterface) NeighList(linkIndex, family int) ([]netlink.Neigh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeighList", linkIndex, family)
	ret0, _ := ret[0].([]netlink.Neigh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeighList indicates an expected call of NeighList.
func (mr *MockToolkitInterfaceMockRecorder) NeighList(linkIndex, family any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeighList", reflect.TypeOf((*MockToolkitInterface)(nil).NeighList), linkIndex, family)
}

// NeighSubscribe mocks base method.
func (m *MockToolkitInterface) NeighSubscribe(ch chan<- netlink.NeighUpdate, done <-chan struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeighSubscribe", ch, done)
	ret0, _ := ret[0].(error)
	return ret0
}

// NeighSubscribe indicates an expected call of NeighSubscribe.
func (mr *MockToolkitInterfaceMockRecorder) NeighSubscribe(ch, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeighSubscribe", reflect.TypeOf((*MockToolkitInterface)(nil).NeighSubscribe), ch, done)
}

// NewIPNet mocks base method.
func (m *MockToolkitInterface) NewIPNet(ip net.IP) *net.IPNet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIPNet", ip)
	ret0, _ := ret[0].(*net.IPNet)
	return ret0
}

// NewIPNet indicates an expected call of NewIPNet.
func (mr *MockToolkitInterfaceMockRecorder) NewIPNet(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIPNet", reflect.TypeOf((*MockToolkitInterface)(nil).NewIPNet), ip)
}

// ParseAddr mocks base method.
func (m *MockToolkitInterface) ParseAddr(s string) (*netlink.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAddr", s)
	ret0, _ := ret[0].(*netlink.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAddr indicates an expected call of ParseAddr.
func (mr *MockToolkitInterfaceMockRecorder) ParseAddr(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAddr", reflect.TypeOf((*MockToolkitInterface)(nil).ParseAddr), s)
}

// RouteAdd mocks base method.
func (m *MockToolkitInterface) RouteAdd(route *netlink.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteAdd", route)
	ret0, _ := ret[0].(error)
	return ret0
}

// RouteAdd indicates an expected call of RouteAdd.
func (mr *MockToolkitInterfaceMockRecorder) RouteAdd(route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteAdd", reflect.TypeOf((*MockToolkitInterface)(nil).RouteAdd), route)
}

// RouteDel mocks base method.
func (m *MockToolkitInterface) RouteDel(route *netlink.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteDel", route)
	ret0, _ := ret[0].(error)
	return ret0
}

// RouteDel indicates an expected call of RouteDel.
func (mr *MockToolkitInterfaceMockRecorder) RouteDel(route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteDel", reflect.TypeOf((*MockToolkitInterface)(nil).RouteDel), route)
}

// RouteListFiltered mocks base method.
func (m *MockToolkitInterface) RouteListFiltered(family int, filter *netlink.Route, filterMask uint64) ([]netlink.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteListFiltered", family, filter, filterMask)
	ret0, _ := ret[0].([]netlink.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteListFiltered indicates an expected call of RouteListFiltered.
func (mr *MockToolkitInterfaceMockRecorder) RouteListFiltered(family, filter, filterMask any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteListFiltered", reflect.TypeOf((*MockToolkitInterface)(nil).RouteListFiltered), family, filter, filterMask)
}

// VethPeerIndex mocks base method.
func (m *MockToolkitInterface) VethPeerIndex(link *netlink.Veth) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VethPeerIndex", link)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VethPeerIndex indicates an expected call of VethPeerIndex.
func (mr *MockToolkitInterfaceMockRecorder) VethPeerIndex(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VethPeerIndex", reflect.TypeOf((*MockToolkitInterface)(nil).VethPeerIndex), link)
}
