apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-hbn-l2
  namespace: system
  labels:
    app.kubernetes.io/component: agent-hbn-l2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent-hbn-l2
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: agent-hbn-l2
      labels:
        app.kubernetes.io/component: agent-hbn-l2
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node.t-caas.telekom.com/uninitialized
          operator: Exists
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
          operator: Exists
      hostNetwork: true
      hostPID: true
      containers:
        - args:
            - "--health-addr=[$(HOST_IP)]:7083"
            - "--metrics-addr=[$(HOST_IP)]:7082"
          command:
            - /agent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: ghcr.io/telekom/das-schiff-nwop-agent-hbn-l2:latest
          imagePullPolicy: IfNotPresent
          name: agent-hbn-l2
          ports:
            - containerPort: 7083
              name: health
              protocol: TCP
            - containerPort: 7082
              name: metrics
              protocol: TCP
          securityContext:
            privileged: true
            runAsUser: 0
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: controller-manager
