server:
  interface: 0.0.0.0
  interface: ::0
  access-control: ::/0 allow
  access-control: 0.0.0.0/0 allow
  do-ip4: yes
  do-ip6: yes
  module-config: "dns64 iterator"
  dns64-prefix: 64:ff9b::/96
  dns64-synthall: yes

forward-zone:
  name: "."
  forward-addr: 5.1.66.255
  forward-addr: 185.150.99.255
