# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/network.t-caas.telekom.com_vrfrouteconfigurations.yaml
- bases/network.t-caas.telekom.com_layer2networkconfigurations.yaml
- bases/network.t-caas.telekom.com_nodenetplanconfigs.yaml
- bases/network.t-caas.telekom.com_nodenetworkconfigs.yaml
- bases/network.t-caas.telekom.com_networkconfigrevisions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_layer2networkconfigurations.yaml
#- patches/webhook_in_vrfrouteconfigurations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_vrfrouteconfigurations.yaml
#- patches/cainjection_in_layer2networkconfigurations.yaml
#- patches/cainjection_in_routingtables.yaml
#- patches/cainjection_in_hbrconfigs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
#- path: patches/webhook_in_vrfrouteconfigurations.yaml
#- path: patches/webhook_in_layer2networkconfigurations.yaml
#- path: patches/webhook_in_routingtables.yaml
