// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/telekom/das-schiff-network-operator/pkg/healthcheck (interfaces: FRRInterface,TCPDialerInterface,HealthCheckerInterface)

// Package mock_healthcheck is a generated GoMock package.
package mock_healthcheck

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	corev1 "k8s.io/api/core/v1"
)

// MockFRRInterface is a mock of FRRInterface interface.
type MockFRRInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFRRInterfaceMockRecorder
}

// MockFRRInterfaceMockRecorder is the mock recorder for MockFRRInterface.
type MockFRRInterfaceMockRecorder struct {
	mock *MockFRRInterface
}

// NewMockFRRInterface creates a new mock instance.
func NewMockFRRInterface(ctrl *gomock.Controller) *MockFRRInterface {
	mock := &MockFRRInterface{ctrl: ctrl}
	mock.recorder = &MockFRRInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFRRInterface) EXPECT() *MockFRRInterfaceMockRecorder {
	return m.recorder
}

// GetStatusFRR mocks base method.
func (m *MockFRRInterface) GetStatusFRR() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusFRR")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStatusFRR indicates an expected call of GetStatusFRR.
func (mr *MockFRRInterfaceMockRecorder) GetStatusFRR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusFRR", reflect.TypeOf((*MockFRRInterface)(nil).GetStatusFRR))
}

// MockTCPDialerInterface is a mock of TCPDialerInterface interface.
type MockTCPDialerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTCPDialerInterfaceMockRecorder
}

// MockTCPDialerInterfaceMockRecorder is the mock recorder for MockTCPDialerInterface.
type MockTCPDialerInterfaceMockRecorder struct {
	mock *MockTCPDialerInterface
}

// NewMockTCPDialerInterface creates a new mock instance.
func NewMockTCPDialerInterface(ctrl *gomock.Controller) *MockTCPDialerInterface {
	mock := &MockTCPDialerInterface{ctrl: ctrl}
	mock.recorder = &MockTCPDialerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTCPDialerInterface) EXPECT() *MockTCPDialerInterfaceMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockTCPDialerInterface) Dial(arg0, arg1 string) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0, arg1)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockTCPDialerInterfaceMockRecorder) Dial(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockTCPDialerInterface)(nil).Dial), arg0, arg1)
}

// MockHealthCheckerInterface is a mock of HealthCheckerInterface interface.
type MockHealthCheckerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerInterfaceMockRecorder
}

// MockHealthCheckerInterfaceMockRecorder is the mock recorder for MockHealthCheckerInterface.
type MockHealthCheckerInterfaceMockRecorder struct {
	mock *MockHealthCheckerInterface
}

// NewMockHealthCheckerInterface creates a new mock instance.
func NewMockHealthCheckerInterface(ctrl *gomock.Controller) *MockHealthCheckerInterface {
	mock := &MockHealthCheckerInterface{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckerInterface) EXPECT() *MockHealthCheckerInterfaceMockRecorder {
	return m.recorder
}

// CheckInterfaces mocks base method.
func (m *MockHealthCheckerInterface) CheckInterfaces() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInterfaces")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckInterfaces indicates an expected call of CheckInterfaces.
func (mr *MockHealthCheckerInterfaceMockRecorder) CheckInterfaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInterfaces", reflect.TypeOf((*MockHealthCheckerInterface)(nil).CheckInterfaces))
}

// CheckReachability mocks base method.
func (m *MockHealthCheckerInterface) CheckReachability() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckReachability")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckReachability indicates an expected call of CheckReachability.
func (mr *MockHealthCheckerInterfaceMockRecorder) CheckReachability() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckReachability", reflect.TypeOf((*MockHealthCheckerInterface)(nil).CheckReachability))
}

// CheckAPIServer mocks base method.
func (m *MockHealthCheckerInterface) CheckAPIServer(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAPIServer", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAPIServer indicates an expected call of CheckAPIServer.
func (mr *MockHealthCheckerInterfaceMockRecorder) CheckAPIServer(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAPIServer", reflect.TypeOf((*MockHealthCheckerInterface)(nil).CheckAPIServer), ctx)
}

// TaintsRemoved mocks base method.
func (m *MockHealthCheckerInterface) TaintsRemoved() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaintsRemoved")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TaintsRemoved indicates an expected call of TaintsRemoved.
func (mr *MockHealthCheckerInterfaceMockRecorder) TaintsRemoved() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaintsRemoved", reflect.TypeOf((*MockHealthCheckerInterface)(nil).TaintsRemoved))
}

// RemoveTaints mocks base method.
func (m *MockHealthCheckerInterface) RemoveTaints(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTaints", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTaints indicates an expected call of RemoveTaints.
func (mr *MockHealthCheckerInterfaceMockRecorder) RemoveTaints(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTaints", reflect.TypeOf((*MockHealthCheckerInterface)(nil).RemoveTaints), ctx)
}

// UpdateReadinessCondition mocks base method.
func (m *MockHealthCheckerInterface) UpdateReadinessCondition(ctx context.Context, status corev1.ConditionStatus, reason, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReadinessCondition", ctx, status, reason, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReadinessCondition indicates an expected call of UpdateReadinessCondition.
func (mr *MockHealthCheckerInterfaceMockRecorder) UpdateReadinessCondition(ctx, status, reason, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadinessCondition", reflect.TypeOf((*MockHealthCheckerInterface)(nil).UpdateReadinessCondition), ctx, status, reason, message)
}
